### ISSUE TITLE
PABanking: Add support for FCOIS

### ISSUE THREAD

**Issue by klingo** [klingo/ESO-PersonalAssistant#62]
Add support for [FCOIS](https://www.esoui.com/downloads/info630-FCOItemSaver.html) to PABanking.

----

**hagermanj**
> Also I was wondering if your addon is compatible with FCOItemsaver. i.e. if you have something locked in your backpack that it will not auto deposit into your bank.

**Asurason**
> A integration of FCO ItemSaver would be awesome to automatically put marked Items in Bank, Trash.
>
> For Example:
> * Items that marked as analyse => Put in Bank
> * Items that marked to sell in Guildbank => Put in Bank
> * Items that marked to sell => Put in Trash so it get sold next time automatically.
> * ...

**BringerOfOmens**
> Being able to create custom banking rules per toon using the FCO item tags would be a huge benefit to your already spectacular add-on.
>
> Being able to create custom rules to apply a FCO item tag based on what was looted would be outstanding

----

## Implementation/Release Status

**Locked**
- [x] Prevent locked items from selling (2.4.2 - #163)
- [x] Prevent locked items from depositing/withdrawing (2.5.18 - #378)

**Marked for research**
- [x] Deposit/Withdraw to Bank/Inventory dropdown (2.5.18 - #378)

**Marked for selling**
- [x] Auto-sell items marked for selling (2.4.2 - #163)

**Marked for deconstruction**
- [x] Deposit/Withdraw to Bank/Inventory dropdown (2.5.18 - #378)

**Marked for improvement**
- [x] Deposit/Withdraw to Bank/Inventory dropdown (2.5.18 - #378)

**Marked for selling at guildstore**
- [x] Deposit/Withdraw to Bank/Inventory dropdown (2.5.18 - #378)

**Marked as intricate**
- [x] Deposit/Withdraw to Bank/Inventory dropdown (2.5.18 - #378)

**Added to Gear 1..5**
- [ ] Deposit/Withdraw to Bank/Inventory dropdown (tbd)

**Dynamic icons 1..30**
- [ ] Deposit/Withdraw to Bank/Inventory dropdown (tbd)

## Priorities
1. Locked (from deposit/withdraw)
2. Marked for deconstruction
3. Marked for research
4. Marked for selling at guildstore
5. Dynamic icons
6. Marked as intricate

**Comment by klingo** [comment]
First integration with "marked for selling" and "locked" is planned for Version 2.4.2!
